version: "3.3"

services:
  postgres-room-103-db:
    image: postgres:16
    container_name: postgres-room-103-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_db
    ports:
      - "54103:5432"